### ISSUE TITLE
Missing mass values?

### ISSUE THREAD

**Issue by rfellers** [HUPO-PSI/psi-mod-CV#20]
Hello,

I have a question about potentially missing mass values. For example, [MOD:00661](https://www.ebi.ac.uk/ols/ontologies/mod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMOD_00661&viewMode=All&siblings=false) seems to have enough "context" to warrant mass values to be populated. Instead, one must look to the first child ([MOD:00724](https://www.ebi.ac.uk/ols/ontologies/mod/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMOD_00724&viewMode=All&siblings=false)) to see mass values assigned. There are many more examples of this: MODs 658-663, 665, 673, 678. I could likely find more if needed. Is there a reason why masses are not assigned at these levels?

Why does this matter to me you might ask? Because Uniprot entry [O43676](https://www.uniprot.org/uniprot/O43676#ptm_processing) (and likely others) defined methyl histidine using the ID 'Methylhistidine' which is mapped to MOD:00661 in Uniprot's [ptmlist](https://www.uniprot.org/docs/ptmlist). This means our searching logic cannot assign a proper mass to the PTM without additional logic.

Thoughts? Thanks!

**Comment by edeutsch** [comment]
I don't know the answer myself. Maybe @pabinz does? One could imagine a policy where only leaf nodes are given masses. But it seems that N-phosphorylated residue has a DiffMono, so it seems that this is unevenly applied if so. Seems like an oversight to me. Would be fine with me to add it.

**Comment by pabinz** [comment]
PSI-MOD is growing organically, and this type of “ambiguity” MOD (not the final leaf) can of course be annotated with a DiffMono, as there is no ambiguity at this level.
Therefore yes, it is to be added.


De : Eric Deutsch <notifications@github.com>
Envoyé : samedi 30 mai 2020 05:23
À : HUPO-PSI/psi-mod-CV <psi-mod-CV@noreply.github.com>
Cc : Binz Pierre-Alain <Pierre-Alain.Binz@chuv.ch>; Mention <mention@noreply.github.com>
Objet : Re: [HUPO-PSI/psi-mod-CV] Missing mass values? (#20)


I don't know the answer myself. Maybe @pabinz<https://github.com/pabinz> does? One could imagine a policy where only leaf nodes are given masses. But it seems that N-phosphorylated residue has a DiffMono, so it seems that this is unevenly applied if so. Seems like an oversight to me. Would be fine with me to add it.

**Comment by pmt706** [comment]
So, here's the issue... Some amino acids can be multiply modified... For instance, MOD:00658, which you mention above (methylated arginine) has children: MOD:00414 (monomethylated arginine) and MOD:00783 (dimethylated arginine) and MOD:01669 (trimethylated arginine)... which themselves have terminal leaf node children.

In this case, the fix will be to generate a "monomethylated histidine" entry and have both of the two positionional isomers (MOD:00322, 1'-methyl-L-histidine, and MOD:00082, 3'-methyl-L-histidine) point to that term, which will have a diffMono and then put that new entry under is_a MOD:00724 ! N-methylated L-histidine.... and then talk to the UniProt folks and have them direct the crossref to the new term.  

Just adding the diff mass/formulae won't work here because, although it hasn't been reported, you could very easily have methylation at both 1' and 3' positions which would be a dimethylated histidine and wouldn't share the same diffMono!  I'll work on the new term and will queue it up.

**Comment by pmt706** [comment]
This will be the new term once the preceding commits take place:

[Term]
id: MOD:02038
name: monomethylated L-histidine
def: "A protein modification that effectively replaces one hydrogen atom of an L-histidine residue with one methyl group." [DeltaMass:215, OMSSA:77, Unimod:34#H]
subset: PSI-MOD-slim
synonym: "Me1His" EXACT PSI-MOD-label []
synonym: "Methyl" RELATED PSI-MS-label []
synonym: "methylh" EXACT OMSSA-label []
xref: DiffAvg: "14.03"
xref: DiffFormula: "C 1 H 2 N 0 O 0"
xref: DiffMono: "14.015650"
xref: Formula: "C 7 H 9 N 3 O 1"
xref: MassAvg: "151.17"
xref: MassMono: "151.074562"
xref: Origin: "H"
xref: Source: "natural"
xref: TermSpec: "none"
xref: Unimod: "Unimod:34"
is_a: MOD:00599 ! monomethylated residue
is_a: MOD:00724 ! N-methylated L-histidine
