### ISSUE TITLE
UniMod vs Unimod

### ISSUE THREAD

**Issue by pmt706** [HUPO-PSI/psi-mod-CV#22]
PSI-MOD has all UniMod, however Unimod is the preferred format.  Would anyone have major issues with changing all UniMod's to Unimod?

**Comment by pmt706** [comment]
http://www.unimod.org/unimod_help.html

**Comment by edeutsch** [comment]
no objections from me. If it breaks any of my code, I can pretty easily fix. I probably upper() it all anyway because in the Unimod OBO file, everything is all caps:
```
[Term]
id: UNIMOD:1
name: Acetyl
def: "Acetylation." [RESID:AA0048, RESID:AA0049, ....
```
But it seems like it is generally understood that capitalization is not important for curie prefixes. And the resource itself should be referred to as Unimod.

In any case, it seems clear that UniMod is an incorrect form and should be changed

**Comment by ricardblum** [comment]
No objections from me for changing UniMod to Unimod.

All the best,

Sylvie.

Professor Sylvie RICARD-BLUM
Pericellular and Extracellular Supramolecular Assemblies
UMR 5246 CNRS - University Lyon 1
Institute of Molecular and Supramolecular Chemistry and Biochemistry
University Claude Bernard Lyon 1, 43 Boulevard du 11 novembre 1918
69622 Villeurbanne Cedex, France
Phone: +33(0)4 72 44 82 32
E-mail: sylvie.ricard-blum@univ-lyon1.fr
http://www.icbms.fr
The French Society for Matrix Biology http://www.sfbmec.fr
The International Society for Matrix Biology http://ismb.org


Le 18/06/2020 à 23:33, Eric Deutsch a écrit :

**Comment by pabinz** [comment]
Yes, fine for me to change UniMod -> Unimod
