### ISSUE TITLE
follow up on SF ticket re  proline isomerization

### ISSUE THREAD

**Issue by ValWood** [HUPO-PSI/psi-mod-CV#28]
From
https://sourceforge.net/p/psidev/mod-controlled-vocab-changes/72/

Hi,

I was prompted to look for this ticket based on a ticket on the GO tracker.
https://github.com/geneontology/go-ontology/issues/19927#issuecomment-685499537

Although there are no comments in the original ticket, I found a couple of follow up comments in  e-mail, and it seems complicated. However, it is something we would like to be able to capture if possible.

8-5-2018

Hi Valerie,
Sorry for the delay. We will look at the reference reporting the prolyl isomerization of CENP-A on a specific proline residue and will give you our feedback as soon as possible.
Best wishes.
Sylvie.

Hi Valerie,
This isomerization is not straightforward to describe as it does not only involve the proline residue. In fact here we talk about a prolyl isomerization cis-trans that is function of the relative geometry of the amide bond at the nterm of the proline residue and in particular of the carbonyl moiety of the previous residue. The proline itself does not change at all in this isomerization. We would need to model an isomerization of a pair of residues and not of a single residue.
Maybe one should add the term as child of MOD:000664  stereoisomerized residue  with source being a double residue including Proline And child of MOD:000915 modified L-proline residue
Will check this

Pierre-Alain

**Comment by pmt706** [comment]
I think we can generate a term for this. After many years!

**Comment by ricardblum** [comment]
I agree!

Best,

Sylvie.

Le 01/12/2020 à 17:16, pmt706 a écrit :

**Comment by ValWood** [comment]
Great!

**Comment by pmt706** [comment]
What do you all think about these two terms to handle the two conformations?  Luckily there are two ChEBI entries that represent these two entities.  It needs adjacency since it's not within the amino acid, but between two amino acids and I chose adjacency to amino acid "X".  They can't be children of stereoisomerized residue (MOD:00664) unless we change the definition of that entry because it refers to D and L isomers that don't really apply to the "rotamers" in this case.

[Term]
id: MOD:02029
name: cis-peptidyl-proline
def: "A protein modification that effectively converts two adjacent source amino acid residues, one of which L-proline into one in which the proline is in the cis orientation omega=0" [ChEBI:83833, PubMed:15735342, PubMed:15311922, PubMed:24116866]
xref: DiffAvg: "0.00"
xref: DiffFormula: "C 0 H 0 N 0 O 0"
xref: DiffMono: "0.000000"
xref: Origin: "X, P"
xref: Source: "natural"
xref: TermSpec: "none"
is_a: MOD:00915 ! modified L-proline residue

[Term]
id: MOD:02030
name: trans-peptidyl-proline
def: "A protein modification that effectively converts two adjacent source amino acid residues, one of which L-proline into one in which the proline is in the trans orientation omega=180" [ChEBI:83834, PubMed:15735342, PubMed:15311922, PubMed:24116866]
xref: DiffAvg: "0.00"
xref: DiffFormula: "C 0 H 0 N 0 O 0"
xref: DiffMono: "0.000000"
xref: Origin: "X, P"
xref: Source: "natural"
xref: TermSpec: "none"
is_a: MOD:00915 ! modified L-proline residue

**Comment by pmt706** [comment]
I welcome any changes as I'm not wedded to either the name nor the definition!

**Comment by edeutsch** [comment]
Seems fine to me, but with my understanding of chemistry I can't tell a proline from a praline, so I am no final authority.

**Comment by ValWood** [comment]
I'm  also not an expert, but looks good!

**Comment by pabinz** [comment]
I would slightly change the name and  definition as follows:



[Term]
id: MOD:02029
name: cis-peptidyl-L-proline
def: "A protein modification that effectively specifies the boundary conformation of two adjacent source amino acid residues, the second (C-term side)  being a L-proline, where the carbonyl group of the amide bond of the N-side of the L-proline is positioned such as the organodiyl group is in the cis orientation (omega=0)" [ChEBI:83833, PubMed:15735342, PubMed:15311922, PubMed:24116866]
xref: DiffAvg: "0.00"
xref: DiffFormula: "C 0 H 0 N 0 O 0"
xref: DiffMono: "0.000000"
xref: Origin: "X, P"
xref: Source: "natural"
xref: TermSpec: "none"
is_a: MOD:00915 ! modified L-proline residue

[Term]
id: MOD:02030
name: trans-peptidyl--Lproline
def: "A protein modification that effectively specifies the boundary conformation of two adjacent source amino acid residues, the second (C-term side)  being a L-proline, where the carbonyl group of the amide bond of the N-side of the L-proline is positioned such as the organodiyl group is in the trans orientation (omega=180)" [ChEBI:83834, PubMed:15735342, PubMed:15311922, PubMed:24116866]
xref: DiffAvg: "0.00"
xref: DiffFormula: "C 0 H 0 N 0 O 0"
xref: DiffMono: "0.000000"
xref: Origin: "X, P"
xref: Source: "natural"
xref: TermSpec: "none"
is_a: MOD:00915 ! modified L-proline residue

**Comment by pmt706** [comment]
Great Edits @pabinz .  I'll create a PR with that new term and see if @ricardblum has any corrections/edits, but this looks great.

**Comment by ricardblum** [comment]
Thank you very much Pierre-Alain.  I have no correction or edits but 
PMID 5485910 could be added (torsion angles are ascribed zero values for 
the cis-conformations in polypeptide backbone).

All the best,

Sylvie.

Le 02/12/2020 à 16:19, pmt706 a écrit :
