### ISSUE TITLE
depracated obo.xml

### ISSUE THREAD

**Issue by trishorts** [HUPO-PSI/psi-mod-CV#41]
we rely on this file and download it regularly into our proteomics tool nuget package mzlib.

https://github.com/smith-chem-wisc/mzLib

https://www.nuget.org/packages/mzLib/

https://github.com/HUPO-PSI/psi-mod-CV/commit/959c9cccaf7ced61780ee249bf5dbda15000cbfe

**Comment by pmt706** [comment]
We're no longer updating the .obo.xml file.  Mostly because it was made by a previous maintainer and we have no idea of how to generate that file any more (and the format is no longer really supported by the ontology community).  The Gene ontology has a note about it here(http://geneontology.org/docs/deprecated-products-and-formats/).  There's two potential solutions...

1. We can bring back an old version of the obo.xml into a different branch (with the caveat that the information is out of date)
2. We're adding a OWL file into the master branch (in PR #40) which is an XML-like format (and libraries exist to parse OWL like dotNETRDF(https://www.dotnetrdf.org/api/html/N_VDS_RDF_Ontology.htm)

thoughts? Would Item 2 work or should I add in a branch with the out-dated obo.xml?

**Comment by trishorts** [comment]
I appreciate your situation. We run into similar problems periodically. As a temporary fix, I forked your repo and then added back the last available version of the obo.xml. Our software now refers to that link, which won't break. 

But now we are disconnected from updates to PSI-MOD, which is an unfortunate consequence. I don't know when we'll be able to get someone from our team to build a new reader for the new format. It's like the problem you have in reverse. We had someone that could write xml readers and now we don't. And now we don't have an xml. C' est la vie. 

Feel free to close the issue if you like. I guess i have no expectations that you'll re-release the xml (but it would save us much pain). 

Sincerely thanks for all the other cool things you do and have done. We benefit from this great resource.

**Comment by edeutsch** [comment]
Parsing the .obo file (which is the most up-to-date) is relatively straightforward. Instead of bothering with the XML, maybe you have a coder that can write an obo parser? It's a pretty simple text format.

Also, now that we know that someone really wants it, I will inquire again with a person who *might* have the script that generates the XML from the OBO.

**Comment by pmt706** [comment]
Thanks, and it's appreciated that our inability to continue with the obo.xml format causes you guys pain, and believe me, if there was a simple way for us to generate an obo.xml from an OBO or OWL file, I'd just add that into our build process.  There's a Perl script referenced in the .obo.xml that was used to generate that file that I can't find... Hopefully @edeutsch has some luck!

**Comment by pmt706** [comment]
Hey @rfellers ... do you have an obo parser in c# that you might be able to share with @trishorts?

**Comment by rfellers** [comment]
Sure thing @pmt706 and @trishorts , you can find a simple OBO parser in the TD SDK:
https://github.com/topdownproteomics/sdk/tree/master/src/TopDownProteomics/IO/Obo

**Comment by trishorts** [comment]
Thanks Ryan. That is going to be a huge help!!!

**Comment by rfellers** [comment]
No problem @trishorts. In hindsight, I probably should have pointed you directly here: https://github.com/topdownproteomics/sdk/tree/master/src/TopDownProteomics/IO/PsiMod. It uses that OboParser to specifically parse PSI-MOD.

**Comment by pmt706** [comment]
Awesome @rfellers and sweet that it's open source.  I'm hoping that makes the obo.xml issue (eventually) moot, @trishorts?

**Comment by trishorts** [comment]
yes. this is all really helpful. i'm going to try and integrate ryan's code into mzlib and see how it goes. 

--happy coder!

**Comment by pmt706** [comment]
Glad to hear this worked out.  If you or anyone else has need for the obo.xml in the future, please let us know and we'll figure it out!
