### ISSUE TITLE
UniProt PTM references are not written as CURIEs

### ISSUE THREAD

**Issue by cthoyt** [HUPO-PSI/psi-mod-CV#68]
right now, UniProt post-translational modification references (https://bioregistry.io/registry/uniprot.ptm) are written as PTM-XXXX. 

This isn't CURIE syntax and doesn't make clear what the resource is that these come from. It would be good to switch them all to CURIE syntax using an appropriate prefix. I will send a PR to demonstrate.

**Comment by edeutsch** [comment]
Is UniProt on board with this change? We are using PTM-XXXX because UniProt is using PTM-XXXX:
https://www.uniprot.org/docs/ptmlist.txt

Will they be changing their ptmlist.txt?
They may wish to keep the `PTM-` since this has been part of their identifiers for a long time?

I'm all for moving to proper CURIEs, but we should make sure they're on board, too.

**Comment by cthoyt** [comment]
I haven't seen a standardized approach to the way they expect external resources to handle identifiers, and I've seen quite a few that omit these pseudo-prefixes. However, the Bioregistry also has a way of annotating this situation, so I'd also be happy just to slap a prefix in front of these as they were. I'll update my PR
